baseurl: ""
markdown: redcarpet
redcarpet:
    extensions: [tables]
safe: false
highlighter: true
excerpt_separator: "\n\n\n"
paginate: 5
plugins: [jekyll-paginate]
sitemapurl: "http://shnnosuke.github.io"
port: 4001